version: '3.8'

services:
  db:
    image: jmartynova123/dev-lab3-db:latest
    environment:
      POSTGRES_DB: times
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d times"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: jmartynova123/dev-lab3-back:latest
    environment:
      DATABASE_URI: postgres://myuser:mypassword@db:5432/times
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/times || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: jmartynova123/dev-lab3-front:latest
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
