apiVersion: v2
name: omsk-time
description: A Helm chart for Omsk Time application
type: application
version: 0.1.0
appVersion: "1.1"
dependencies:
  - name: common-lib
    version: 0.1.0
    repository: file://../common-lib
