apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time-app
spec:
  replicas: 3               
  selector:
    matchLabels:             
      app: moscow-time-app
  template:
    metadata:
      labels:
        app: moscow-time-app
    spec:
      containers:
      - name: moscow-time-app
        image: utkanosss/moscow-time-app
        ports:
        - containerPort: 5000 
        resources:           
          limits:
            memory: "128Mi"   
            cpu: "500m"      
          requests:
            memory: "64Mi"   
            cpu: "250m" 
