apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go
  labels:
    app: app-go
spec:
  selector:
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:
        - name: app-go
          image: justcgh/url-shortener-distroless:latest
          ports:
            - containerPort: 8080
  replicas: 3