apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-app
  template:
    metadata:
      labels:
        app: time-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "my-app-role"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/database-config"
    spec:
      containers:
        - name: time-app
          image: meowal/msk-time-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MY_PASS
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MY_PASS
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /vault/config/
              name: vault-config
              readOnly: true
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
      initContainers:
        - name: vault-agent-init
          image: hashicorp/vault:1.18.1
          command:
            - "vault"
            - "agent"
            - "-config=/vault/config/config.hcl"
          volumeMounts:
            - mountPath: /vault/config/
              name: vault-config
              readOnly: true

