# apiVersion: v1

# kind: ConfigMap
# metadata:
#   name: app-python-config
#   labels:
#     {{- include "chart-app-python.labels" . | nindent 4 }}
# data:
#   config.json: |-
# {{ .Files.Get "files/config.json" | indent 4 }}