apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-app-python.fullname" . }}
  labels:
    {{- include "chart-app-python.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-app-python.selectorLabels" . | nindent 4 }}
---

# NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-app-python.fullname" . }}-external
  labels:
    {{- include "chart-app-python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-app-python.selectorLabels" . | nindent 4 }}
