apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-hook
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded

spec:
  template:
    spec:
      containers:
      - name: post-install-job
        image: busybox
        command: ["sh", "-c", "echo 'Post-install Hook Completed for Python App'; sleep 10"]
      restartPolicy: Never

