password: ENC[AES256_GCM,data:MXV0R4F8nz/1,iv:b8rNpdpecTz3R+C2MUC+mAgw352Qof5rl6uXNfbYnsc=,tag:OPHxjzNnJ0o2uxkDE1Qy4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-04T21:04:26Z"
    mac: ENC[AES256_GCM,data:11EN5IVAzkgvCPpDVVP9caBKvj9hFDSiJml7FcuvjsNtK5Y+Fu+2aoXED1DBcY251n7xjc5P/VxfeKqvG0YNFi9nqdrojT8aMLTmgwHoGLN9ncA1GjDukpCe4V74zHA/xlbsi00LA3qyYqRJJ2jXfDqg+OsiX4/nY4Y27DXOtB8=,iv:rslrj8P32i+4vf8sekhqv4VsEmgP85mjhFonnOS1K2g=,tag:EiOCeOO3lWid2o3hCzbAhA==,type:str]
    pgp:
        - created_at: "2025-03-04T21:03:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYGL4POjMwEASAQdAHeIb1FiB8B/1J+l/N+7AryL0UHpGwN1PNTOaPKRKl3Iw
            5VDcAy+pqQkWAaNDNfwaI0vkxdK5VcX3rHNrMbYMK2hKBtQI5kW/uWdRDJwgmWPJ
            1GgBCQIQPjSc51z/WGBMIgaCZ+oOdE7/4ckaZuUNmkE6wv6LoC/GzhP16j33aAH9
            eyaDqVJMOV6PkCh7tz1CsLB6NScSjfmePaRyfC9+YYg9cDRwUd+zVlPy358cpy2r
            pdIzVkeuxOkXOw==
            =eR1P
            -----END PGP MESSAGE-----
          fp: 5E122B618402A7BD8EE1DBDAE1E7C1D76CD61BA9
    unencrypted_suffix: _unencrypted
    version: 3.9.4
