---
- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: compose_version
