- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'

- name:
    Verify Docker Compose installation   command:
      docker-compose --version   register:
        docker_compose_version   changed_when:
          false

- name:
    Show Docker Compose version   debug:
      msg: "Docker Compose installed: {{ docker_compose_version.stdout }}"