apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-python
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: app-python.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-python
            port:
              number: 8001