name: Node CI

on: [push, pull_request]
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd app_nodejs
          npm install

      - name: Lint
        run: |
          npm install -g eslint
          cd app_nodejs
          npx eslint server.js

      - name: Run Tests
        run: |
          cd app_nodejs
          npm test

      # Docker build & push
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd app_nodejs
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-webapp:ci-latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-webapp:ci-latest

      # Snyk Security Scan
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        with:
            command: test ../../app_nodejs
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
